management:
  health.db.enabled: false
  endpoints:    
    web:
      base-path: /
      exposure:
        include: "*"

server:
  port: 9070
  servlet:
    context-path: /api/flights/provider/beta

jetty:
  threadPool:
    maxThreads: 10
    minThreads: 10

redis:
  host: api-clusters-remote-cache
  port: 6379

cache:
  settings:
    catalog-city:
      expire-after-write-time: 60 # minutes

chaos:
  monkey:
    enabled: false
    watcher:
      restController: true
    assaults:
      exceptionsActive: true
      latencyActive: true   
      latencyRangeStart: 3000
      latencyRangeEnd: 10000 
      
spring:
  profiles:
    active: chaos-monkey
        
connector:
   catalog:
      host: api-catalog-varnish:80
      responseTimeout: 1000
      connectionTimeout: 1000
      readTimeout: 1000