management:
  health.db.enabled: false
  endpoints:    
    web:
      base-path: /
      exposure:
        include: "*"

server:
  port: 9080
  servlet:
    context-path: /api/flights/provider/alpha

jetty:
  threadPool:
    maxThreads: 10
    minThreads: 10
    
connector:
   catalog:
      host: api-catalog:6080
      responseTimeout: 1000
      connectionTimeout: 1000
      readTimeout: 1000