management:
  health.db.enabled: false
  endpoints:    
    web:
      base-path: /
      exposure:
        include: "*"

server:
  port: 8070
  servlet:
    context-path: /api/flights/provider/alpha

jetty:
  threadPool:
    maxThreads: 10
    minThreads: 10
    
chaos:
  monkey:
    enabled: false
    watcher:
      restController: true
    assaults:
      exceptionsActive: true
      latencyActive: true   
      latencyRangeStart: 3000
      latencyRangeEnd: 10000  
      
spring:
  profiles:
    active: chaos-monkey
    
connector:
   catalog:
      host: api-catalog-cache:80
      responseTimeout: 1000
      connectionTimeout: 1000
      readTimeout: 1000
cache:
  configuration:
    CATALOG_CITY:
      refreshAfterWriteTime: 5 #MINUTES
      expireAfterWriteTime: 10 #MINUTES
      maxSize: 180