management:
  health.db.enabled: false
  endpoints:    
    web:
      base-path: /
      exposure:
        include: "*"

server:
  port: 8070
  servlet:
    context-path: /api/flights/provider/alpha

jetty:
  threadPool:
    maxThreads: 10
    minThreads: 10

redis:
  host: localhost
  port: 5079

cache:
  settings:
    catalog-city:
      expire-after-write-time: 60 # minutes

chaos:
  monkey:
    enabled: false
    watcher:
      restController: true
    assaults:
      exceptionsActive: true
      latencyActive: true   
      latencyRangeStart: 3000
      latencyRangeEnd: 10000   
      
spring:
  profiles:
    active: chaos-monkey
  jackson:
    default-property-inclusion: non_null

connector:
   catalog:
      host: localhost:6070
      responseTimeout: 1000
      connectionTimeout: 1000
      readTimeout: 1000