management:
  health.db.enabled: false
  endpoints:    
    web:
      base-path: /
      exposure:
        include: "*"

server:
  port: 4070
  servlet:
    context-path: /api/flights/clusters

jetty:
  threadPool:
    maxThreads: 10
    minThreads: 10

chaos:
  monkey:
    enabled: false
    watcher:
      restController: true
    assaults:
      exceptionsActive: true
      latencyActive: true   
      latencyRangeStart: 10
      latencyRangeEnd: 5000  
      
spring:
  profiles:
    active: default
    
redis:
   db:
      host: localhost
      port: 6079    
   remote-cache:
      host: localhost
      port: 5079     
    
connector:
   catalog:
      host: localhost:6080
      responseTimeout: 2000
      connectionTimeout: 2000
      readTimeout: 2000
   pricing:
      host: localhost:5070
      responseTimeout: 10000
      connectionTimeout: 10000
      readTimeout: 10000   
   itineraries-search:
      host: localhost:7070
      responseTimeout: 10000
      connectionTimeout: 10000
      readTimeout: 10000 
cache:
  configuration:
    CATALOG_CITY:
       expireAfterWriteTime: 10 #MINUTES 