management:
  health.db.enabled: false
  endpoints:    
    web:
      base-path: /
      exposure:
        include: "*"

server:
  port: 4070
  servlet:
    context-path: /api/flights/clusters

jetty:
  threadPool:
    maxThreads: 10
    minThreads: 10
    
connector:
   catalog:
      host: localhost:6080
      responseTimeout: 2000
      connectionTimeout: 2000
      readTimeout: 2000
   pricing:
      host: localhost:5080
      responseTimeout: 10000
      connectionTimeout: 10000
      readTimeout: 10000   
   itineraries-search:
      host: localhost:7080
      responseTimeout: 10000
      connectionTimeout: 10000
      readTimeout: 10000         