management:
  health.db.enabled: false
  endpoints:    
    web:
      base-path: /
      exposure:
        include: "*"

server:
  port: 5070
  servlet:
    context-path: /api/flights/pricing

jetty:
  threadPool:
    maxThreads: 10
    minThreads: 10

chaos:
  monkey:
    enabled: true
    watcher:
      restController: true
    assaults:
      exceptionsActive: true
      latencyActive: true   
      latencyRangeStart: 5000
      latencyRangeEnd: 10000
      
spring:
  profiles:
    active: chaos-monkey
  flyway:
    locations: classpath:db/migration
    sql-migration-prefix: V
    repeatable-sql-migration-prefix: R
    sql-migration-separator: __
    sql-migration-suffixes: .sql
  datasource:
    url: "jdbc:mysql://api-pricing-db:3306/flights_pricing?autoReconnect=true"
    username: root
    password: muppet
    driverClassName: com.mysql.cj.jdbc.Driver
    validation-query: select 1;
    maxActive: 100
  jpa:
    show-sql: false
    generate-ddl: false    
    properties:    
      hibernate:
        ejb.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy                
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl.auto: validate